name: Bug Report
description: Ein Fehler, der gefixt werden sollte.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        ## Prüfe vor dem Erstellen, ob das Problem bereits gemeldet wurde.
  - type: textarea
    id: description
    attributes:
      label: Detaillierte Fehlerbeschreibung
      description: |
        Beschreibe genau, was nicht funktioniert.
        Füge wenn möglich Screenshots oder Fehlermeldungen hinzu.
        Sei so spezifisch wie möglich.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduzierbarkeit
      description: |
        Liste alle Schritte auf, die zum Fehler führen.
        Nummeriere die Schritte chronologisch.
        Beschreibe den Ausgangspunkt (z.B. "Startseite von pr0.app").
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Erwartetes Verhalten
      description: |
        Erkläre, wie die Funktion eigentlich arbeiten sollte.
        Beschreibe das gewünschte Ergebnis.
  - type: textarea
    id: env
    attributes:
      label: Umgebungsinformationen
      description: |
        Browser und Version (z.B. Firefox 129).
        Betriebssystem (z.B. Windows 10).
        Bei mobilen Geräten: Gerät und OS-Version.
  - type: textarea
    id: rest
    attributes:
      label: Noch was?
      description: Was du uns schon immer mal sagen wolltest

