blank_issues_enabled: false
contact_links:
  - name: pr0gramm.com-Support
    url: https://pr0gramm.com/contact
    about: Hier bekommst du Support und kannst Fragen stellen. Wenn du dir nicht sicher bist, wähle diese Option.
